version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."

  build:
    commands:
      - echo "Running Docker build..."
      - docker build -t todo-list-app .

  post_build:
    commands:
      - echo "Deploying to EC2..."
      - aws ssm send-command
          --instance-ids "i-0679e0ae6042ce455"
          --document-name "AWS-RunShellScript"
          --parameters 'commands=["cd /home/ubuntu/todo-list-app","git pull origin chapter2-cicd-partB","git checkout chapter2-cicd-partB","docker compose build","docker compose up -d"]'
          --comment "Deploy Todo App"
