version: 0.2

phases:
  install:
    commands:
      - yum install -y openssh-clients
      - mkdir -p ~/.ssh
      - aws secretsmanager get-secret-value --secret-id chapter2/ec2-ssh-key --query SecretString --output text > /tmp/ec2-key.pem
      - chmod 400 /tmp/ec2-key.pem

  build:
    commands:
      - echo "Preparing deployment..."

  post_build:
    commands:
      - echo "Deploying to EC2..."
      - ssh-keyscan -H 34.201.104.212 >> ~/.ssh/known_hosts
      - >
        ssh -i /tmp/ec2-key.pem
        ubuntu@34.201.104.212
        "cd ~/todo-list-app &&
         git pull origin main &&
         docker compose build &&
         docker compose up -d"